version: "3.7"
services:

    server:
        build: ./resources/server
        container_name: "musicbrainz_server"
        depends_on:
            - redis
            - postgres
        restart: unless-stopped
        command: /bin/bash /resources/scripts/InitialSetup.sh
        volumes:
            - .:/musicbrainz
        ports: 
            - "5000:5000"
        networks:
            - MBNet

    postgres:
        build: ./resources/database
        container_name: "postgres"
        volumes:
            - type: bind
              source: ./resources/database/db-data
              target: /var/lib/postgresql/data
        networks:
            - MBNet

    redis:
        image: redis
        container_name: "redis"
        networks:
            - MBNet

networks:
    MBNet:
