FROM ubuntu:16.04

ARG POSTGRES_VERSION=9.5

RUN apt-get update
RUN apt-get install \
    postgresql-client-$POSTGRES_VERSION -y

RUN apt-get install git -y
RUN apt-get install redis-server -y
RUN apt-get install build-essential curl -y

RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -
RUN apt-get install nodejs -y

RUN apt-get install gnupg -y
RUN apt-get install apt-transport-https

RUN npm install -g yarn

RUN apt-get install \
    libdb-dev \
    libexpat1-dev \
    libicu-dev \
    liblocal-lib-perl \
    libpq-dev \
    libxml2 \
    libxml2-dev \
    cpanminus \
    pkg-config -y

RUN perl -Mlocal::lib

WORKDIR /musicbrainz